# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Politicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('consultas', models.CharField(max_length=30)),
                ('examenes', models.CharField(max_length=30)),
                ('evaluacion', models.CharField(max_length=30)),
                ('tarea', models.CharField(max_length=30)),
            ],
        ),
    ]
