# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_politicas',
            name='consultas',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info_politicas',
            name='evaluacion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info_politicas',
            name='examenes',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info_politicas',
            name='tarea',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='info_politicas',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='objectivo',
            field=models.CharField(max_length=300),
        ),
    ]
